### ISSUE TITLE
Unsolvable R 4.3 migration

### ISSUE THREAD

**Issue by mfansler** [conda-forge/rhumba-feedstock#15]
The recipe's strong constraint on `libmamba` makes it incompatible with R 4.3 migration due to newer `r-base` builds only linking to `libcurl=8`. That is, the older `libmamba` builds require `libcurl=7`.

Either 

1. This recipe needs a rebuild with newer `libmamba`; or 
2. `libmamba` needs to build a special v0.25 that links against `libcurl=8`.

**Comment by marimeireles** [comment]
Thanks for opening this issue! :)
Have you tried to make this migration yourself locally by using `conda build`?

I'm thinking about just relaxing the constraints for libmamba and updating to the latest R.
I guess @SylvainCorlay added an upper bound for it, has micromamba introduced breaking changes after 0.26?

Thanks.

**Comment by mfansler** [comment]
Thanks for replying. I put in a PR. The C API header file had no changes until v1.4.5, so I'm trying that as a new upper bound.
